# “What is the total revenue generated by each customer, along with their region?”
WITH t AS (
    SELECT 
        c.customer_id,
        c.customer_name,
        c.region,
        o.order_id,
        i.order_item_id,
        (i.quantity * p.price) AS total_revenue
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    JOIN order_items i ON o.order_id = i.order_id
    JOIN products p ON i.product_id = p.product_id
)
SELECT 
    customer_name,
    region,
    SUM(total_revenue) AS customer_revenue
FROM t
GROUP BY customer_name, region
ORDER BY customer_revenue DESC;


# “Which products generate the highest revenue?”
WITH t2 AS (
    SELECT 
        p.product_id,
        p.product_name,
        p.category,
        SUM(p.price * i.quantity) AS total_revenue
    FROM products p
    JOIN order_items i ON p.product_id = i.product_id
    GROUP BY p.product_id, p.product_name, p.category
)
SELECT 
    product_name,
    category,
    total_revenue,
    DENSE_RANK() OVER (ORDER BY total_revenue DESC) AS revenue_rank
FROM t2
ORDER BY revenue_rank;


# “Who are the repeat customers?”
SELECT 
    c.customer_id,
    c.customer_name,
    COUNT(DISTINCT o.order_id) AS order_count
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(DISTINCT o.order_id) > 1
ORDER BY order_count DESC;


#“How is revenue distributed over time?”

WITH monthly_revenue AS (
    SELECT
        DATE_FORMAT(o.order_date, '%Y-%m') AS month,
        SUM(i.quantity * p.price) AS total_revenue
    FROM orders o
    JOIN order_items i ON o.order_id = i.order_id
    JOIN products p ON i.product_id = p.product_id
    GROUP BY DATE_FORMAT(o.order_date, '%Y-%m')
)
SELECT
    month,
    total_revenue,
    LAG(total_revenue) OVER (ORDER BY month) AS prev_month_revenue,
    total_revenue - LAG(total_revenue) OVER (ORDER BY month) AS mom_growth
FROM monthly_revenue
ORDER BY month;
